import { create } from "zustand";
import { initialTimeline } from "@/mocks/demo";
import type { Aspect, Timeline } from "@/types";
type State={timeline:Timeline;past:Timeline[];future:Timeline[];selectedId:string|null;playhead:number;zoom:number;silences:boolean;setPlayhead:(n:number)=>void;setZoom:(n:number)=>void;select:(id:string|null)=>void;setAspect:(a:Aspect)=>void;moveItem:(track:number,id:string,delta:number)=>void;trimItem:(track:number,id:string,edge:"start"|"end",delta:number)=>void;deleteSelected:()=>void;splitSelected:()=>void;removeSilences:()=>void;shorten:()=>void;replace:(t:Timeline)=>void;undo:()=>void;redo:()=>void;reset:()=>void};
const clone=(t:Timeline)=>structuredClone(t);
export const useTimelineStore=create<State>((set,get)=>{
 const commit=(fn:(t:Timeline)=>Timeline)=>set(s=>({past:[...s.past,clone(s.timeline)].slice(-30),timeline:fn(clone(s.timeline)),future:[]}));
 return {timeline:clone(initialTimeline),past:[],future:[],selectedId:null,playhead:0,zoom:1,silences:false,setPlayhead:n=>set({playhead:n}),setZoom:n=>set({zoom:n}),select:id=>set({selectedId:id}),setAspect:a=>commit(t=>({...t,aspect:a})),moveItem:(track,id,delta)=>commit(t=>{const it=t.tracks[track].items.find(x=>x.id===id);if(it){const d=Math.max(-it.start,delta);it.start+=d;it.end+=d}return t}),trimItem:(track,id,edge,delta)=>commit(t=>{const it=t.tracks[track].items.find(x=>x.id===id);if(it){if(edge==="start")it.start=Math.max(0,Math.min(it.end-.5,it.start+delta));else it.end=Math.max(it.start+.5,it.end+delta)}return t}),deleteSelected:()=>{const id=get().selectedId;if(!id)return;commit(t=>{t.tracks.forEach(tr=>tr.items=tr.items.filter(x=>x.id!==id));return t});set({selectedId:null})},splitSelected:()=>{const {selectedId,playhead}=get();if(!selectedId)return;commit(t=>{for(const tr of t.tracks){const i=tr.items.findIndex(x=>x.id===selectedId&&playhead>x.start&&playhead<x.end);if(i>=0){const it=tr.items[i];tr.items.splice(i,1,{...it,end:playhead},{...it,id:`${it.id}-split-${Date.now()}`,start:playhead});break}}return t})},removeSilences:()=>{commit(t=>{t.tracks.forEach(tr=>tr.items.forEach(it=>{if(it.start>=10.5){it.start-=.5;it.end-=.5}}));return t});set({silences:true})},shorten:()=>commit(t=>{t.tracks.forEach(tr=>tr.items.forEach(it=>it.end=Math.min(it.end,30)));return t}),replace:(t:Timeline)=>set(s=>({past:[...s.past,clone(s.timeline)].slice(-30),timeline:clone(t),future:[]})),undo:()=>set(s=>s.past.length?{timeline:s.past.at(-1)!,past:s.past.slice(0,-1),future:[clone(s.timeline),...s.future]}:s),redo:()=>set(s=>s.future.length?{timeline:s.future[0],future:s.future.slice(1),past:[...s.past,clone(s.timeline)]}:s),reset:()=>set({timeline:clone(initialTimeline),past:[],future:[],selectedId:null,playhead:0,silences:false})};
});
