"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { Bot, Captions, Copy, Film, Music2, Pause, Play, Redo2, RotateCcw, Scissors, Send, Sparkles, Trash2, Undo2, Upload } from "lucide-react";
import { transcriptWords } from "@/mocks/demo";
import { api } from "@/lib/api";
import { useToast } from "@/components/shared/ui";
import { useTimelineStore } from "./store";
const duration=32; const trackIcons={video:Film,caption:Captions,music:Music2};
export function TimelineEditor(){
 const videoRef=useRef<HTMLVideoElement>(null); const toast=useToast(); const s=useTimelineStore(); const setPlayhead=s.setPlayhead; const [playing,setPlaying]=useState(false); const [style,setStyle]=useState("bold"); const [focus,setFocus]=useState(50); const [command,setCommand]=useState(""); const [brand,setBrand]=useState("#ffe45e"); const [font,setFont]=useState("Geist"); const [json,setJson]=useState(false); const pixels=30*s.zoom;
 const activeWords=useMemo(()=>transcriptWords.filter(w=>s.playhead>=w.start&&s.playhead<=w.end+1.1).slice(0,5),[s.playhead]);
 useEffect(()=>{const v=videoRef.current;if(!v)return;const onTime=()=>{setPlayhead(v.currentTime);if(v.currentTime>=24){v.pause();setPlaying(false)}};v.addEventListener("timeupdate",onTime);return()=>v.removeEventListener("timeupdate",onTime)},[setPlayhead]);
 const seek=(n:number)=>{s.setPlayhead(n);if(videoRef.current)videoRef.current.currentTime=n}; const toggle=()=>{const v=videoRef.current;if(!v)return;if(v.paused){if(v.currentTime>=24)v.currentTime=0;void v.play();setPlaying(true)}else{v.pause();setPlaying(false)}};
  const run=async()=>{if(!command.trim())return;const res=await api.assistantCommand(s.timeline.id,command);const c=command.toLowerCase();if(res.timeline){s.replace(res.timeline)}else{if(c.includes("30")||c.includes("short"))s.shorten();if(c.includes("silence"))s.removeSilences();if(c.includes("punch"))setStyle("karaoke")}toast(`AI applied: “${command}”`);setCommand("")};
 return <div className="editor-shell"><div className="editor-top"><section className="preview-panel"><div className="preview-toolbar"><div>{(["9:16","1:1","16:9"] as const).map(a=><button className={s.timeline.aspect===a?"active":""} onClick={()=>s.setAspect(a)} key={a}>{a}</button>)}</div><label>Speaker focus <input type="range" min="0" max="100" value={focus} onChange={e=>setFocus(+e.target.value)}/></label></div><div className={`video-frame aspect-${s.timeline.aspect.replace(":","-")}`}><video ref={videoRef} src="/demo/sample.mp4" style={{objectPosition:`${focus}% center`}} onClick={toggle}/><div className={`live-caption caption-${style}`} style={{color:style==="bold"?brand:"white",fontFamily:font}}>{activeWords.map((w,i)=><span className={style==="karaoke"&&i===0?"active":""} key={`${w.start}-${w.word}`}>{w.word} </span>)}</div><button className="big-play" onClick={toggle}>{playing?<Pause fill="currentColor"/>:<Play fill="currentColor"/>}</button></div><div className="player-controls"><button onClick={toggle}>{playing?<Pause/>:<Play/>}</button><span>{s.playhead.toFixed(1)}s / 24.0s</span><input type="range" min="0" max="24" step=".05" value={Math.min(s.playhead,24)} onChange={e=>seek(+e.target.value)}/></div></section>
 <aside className="editor-inspector"><div className="inspector-tabs"><button className="active">Captions</button><button>Brand</button></div><h4>CAPTION STYLE</h4><div className="caption-presets">{[["bold","BOLD","YELLOW"],["minimal","Minimal","white"],["karaoke","Karaoke","highlight"]].map(x=><button className={style===x[0]?"active":""} onClick={()=>setStyle(x[0])} key={x[0]}><strong>{x[1]}</strong><small>{x[2]}</small></button>)}</div><h4>BRAND KIT</h4><label className="brand-upload"><Upload/> Upload logo<input type="file" hidden/></label><div className="brand-fields"><label>Caption colour<input type="color" value={brand} onChange={e=>setBrand(e.target.value)}/></label><label>Typeface<select value={font} onChange={e=>setFont(e.target.value)}><option>Geist</option><option>Arial Black</option><option>Georgia</option></select></label></div><button className="json-button" onClick={()=>setJson(!json)}><Copy/> {json?"Hide":"View"} Timeline JSON</button>{json&&<pre className="timeline-json">{JSON.stringify(s.timeline,null,2)}</pre>}</aside></div>
 <section className="timeline-panel"><div className="timeline-toolbar"><div><button onClick={s.undo} disabled={!s.past.length}><Undo2/> Undo</button><button onClick={s.redo} disabled={!s.future.length}><Redo2/> Redo</button><button onClick={s.splitSelected}><Scissors/> Split</button><button onClick={s.deleteSelected}><Trash2/> Delete</button></div><label><input type="checkbox" checked={s.silences} onChange={e=>e.target.checked?s.removeSilences():s.reset()}/> Remove silences</label><label>Zoom <input type="range" min=".65" max="2" step=".05" value={s.zoom} onChange={e=>s.setZoom(+e.target.value)}/></label><button onClick={s.reset}><RotateCcw/> Reset to AI version</button></div><div className="timeline-scroll"><div className="timeline-ruler" style={{width:duration*pixels+110}}>{Array.from({length:9},(_,i)=><span key={i} style={{left:110+i*4*pixels}}>{i*4}s</span>)}</div><div className="tracks" style={{width:duration*pixels+110}}><div className="playhead" style={{left:110+s.playhead*pixels}} onMouseDown={()=>{const move=(e:MouseEvent)=>seek(Math.max(0,Math.min(duration,(e.clientX-300)/pixels)));const up=()=>{removeEventListener("mousemove",move);removeEventListener("mouseup",up)};addEventListener("mousemove",move);addEventListener("mouseup",up)}}/><button className="playhead-handle" style={{left:103+s.playhead*pixels}} onClick={toggle}>{playing?<Pause/>:<Play/>}</button>{s.timeline.tracks.map((track,ti)=>{const Icon=trackIcons[track.type];return <div className="track" key={track.type}><div className="track-label"><Icon/><span>{track.type}</span></div><div className="track-lane" onClick={e=>seek(Math.max(0,(e.clientX-e.currentTarget.getBoundingClientRect().left)/pixels))}>{track.items.map(item=><div key={item.id} className={`track-item ${track.type} ${s.selectedId===item.id?"selected":""}`} style={{left:item.start*pixels,width:(item.end-item.start)*pixels}} onClick={e=>{e.stopPropagation();s.select(item.id)}} onMouseDown={e=>{if((e.target as HTMLElement).dataset.edge)return;const x=e.clientX;const move=(ev:MouseEvent)=>s.moveItem(ti,item.id,(ev.clientX-x)/pixels);const up=()=>{removeEventListener("mousemove",move);removeEventListener("mouseup",up)};addEventListener("mousemove",move);addEventListener("mouseup",up)}}><i data-edge="start" onMouseDown={e=>{e.stopPropagation();const x=e.clientX;const move=(ev:MouseEvent)=>s.trimItem(ti,item.id,"start",(ev.clientX-x)/pixels);const up=()=>{removeEventListener("mousemove",move);removeEventListener("mouseup",up)};addEventListener("mousemove",move);addEventListener("mouseup",up)}}/><span>{item.text??item.src??track.type}</span><i data-edge="end" onMouseDown={e=>{e.stopPropagation();const x=e.clientX;const move=(ev:MouseEvent)=>s.trimItem(ti,item.id,"end",(ev.clientX-x)/pixels);const up=()=>{removeEventListener("mousemove",move);removeEventListener("mouseup",up)};addEventListener("mousemove",move);addEventListener("mouseup",up)}}/></div>)}</div></div>})}</div></div></section>
 <section className="assistant-bar"><span><Bot/></span><div><strong>Ask the editing assistant</strong><small>Edits are applied directly to your structured timeline.</small></div><input value={command} onChange={e=>setCommand(e.target.value)} onKeyDown={e=>e.key==="Enter"&&void run()} placeholder='Try “shorten to 30s” or “remove silences”'/><button onClick={()=>void run()}><Sparkles/> Apply <Send/></button></section></div>;
}
