"use client";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { BarChart3, CalendarDays, Clapperboard, Command, Film, FolderOpen, LayoutDashboard, Menu, Search, Sparkles, Workflow, X } from "lucide-react";
const nav = [{ href: "/dashboard", label: "Overview", icon: LayoutDashboard }, { href: "/assets", label: "Assets", icon: FolderOpen }, { href: "/studio/grow-creator", label: "AI Studio", icon: Clapperboard }, { href: "/workflow", label: "Workflow", icon: Workflow }, { href: "/publish", label: "Publish", icon: CalendarDays }, { href: "/insights", label: "Insights", icon: BarChart3 }];
export function AppShell({ children }: { children: React.ReactNode }) {
  const path = usePathname(); const router = useRouter(); const [mobile, setMobile] = useState(false); const [palette, setPalette] = useState(false);
  useEffect(() => { const onKey = (e: KeyboardEvent) => { if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === "k") { e.preventDefault(); setPalette(v => !v); } if (e.key === "Escape") setPalette(false); }; addEventListener("keydown", onKey); return () => removeEventListener("keydown", onKey); }, []);
  const go = (href: string) => { setPalette(false); setMobile(false); router.push(href); };
  return <div className="app-shell"><aside className={`sidebar ${mobile ? "sidebar-open" : ""}`}><div className="brand"><div className="brand-mark"><Sparkles size={17}/></div><span>Creator<span>Ai</span></span><button className="mobile-close" onClick={() => setMobile(false)} aria-label="Close navigation"><X/></button></div><nav>{nav.map(({ href, label, icon: Icon }) => <Link key={href} href={href} className={path.startsWith(href.split("/").slice(0,2).join("/")) ? "active" : ""} onClick={() => setMobile(false)}><Icon size={18}/><span>{label}</span>{label === "AI Studio" && <em>AI</em>}</Link>)}</nav><div className="sidebar-project"><div><Film size={16}/> Current project</div><strong>How to grow as a creator</strong><span><i style={{width:"74%"}}/>74% complete</span></div><button className="profile"><div>KS</div><span><strong>Kunal Suthar</strong><small>Creator workspace</small></span><span>•••</span></button></aside>
  <section className="shell-main"><header className="topbar"><button className="mobile-menu" onClick={() => setMobile(true)} aria-label="Open navigation"><Menu/></button><div className="topbar-title"><small>CREATOR WORKSPACE</small><strong>{nav.find(n => path.startsWith(n.href.split("/").slice(0,2).join("/")))?.label ?? "Overview"}</strong></div><button className="command-button" onClick={() => setPalette(true)}><Search size={16}/><span>Jump to anything...</span><kbd><Command size={12}/> K</kbd></button><div className="status-pill"><i/> All systems operational</div><button className="avatar">KS</button></header><main className="page-wrap">{children}</main></section>
  {palette && <div className="palette-backdrop" onMouseDown={() => setPalette(false)}><div className="palette" onMouseDown={e => e.stopPropagation()}><div><Search/><input autoFocus placeholder="Where do you want to go?"/></div><small>QUICK NAVIGATION</small>{nav.map(({href,label,icon:Icon}) => <button key={href} onClick={() => go(href)}><Icon size={18}/><span>{label}</span><kbd>↵</kbd></button>)}</div></div>}</div>;
}
