import { assets, clips, hooks, initialTimeline, insightMetrics, mappings, projects, scheduledPosts, script, transcriptWords, workflowCards } from "@/mocks/demo";
import type { Asset, Clip, HookVariant, InsightMetric, Mapping, Project, ScheduledPost, Script, Timeline, TranscriptMoment, WorkflowCard } from "@/types";
const MOCK = process.env.NEXT_PUBLIC_USE_MOCK !== "false";
const BASE = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";
const wait = async () => new Promise((resolve) => setTimeout(resolve, 400 + Math.random() * 500));
async function request<T>(path: string, init?: RequestInit, mock?: () => T): Promise<T> { if (MOCK && mock) { await wait(); return structuredClone(mock()); } const response = await fetch(`${BASE}${path}`, { ...init, headers: { "Content-Type": "application/json", ...init?.headers } }); if (!response.ok) throw new Error(`API ${response.status}: ${path}`); return response.json() as Promise<T>; }
export const api = {
  getProjects: () => request<Project[]>("/projects", undefined, () => projects), getAssets: (q = "") => request<Asset[]>(`/assets?q=${encodeURIComponent(q)}`, undefined, () => assets.filter(a => !q || `${a.name} ${a.tags.join(" ")}`.toLowerCase().includes(q.toLowerCase()))), uploadAsset: (file: { name: string; type: string }) => request<Asset>("/assets/upload", { method: "POST", body: JSON.stringify(file) }, () => ({ ...assets[0], id: crypto.randomUUID(), name: file.name })), searchMoments: (q: string) => request<TranscriptMoment[]>(`/assets?q=${encodeURIComponent(q)}`, undefined, () => [{ text: q.toLowerCase().includes("pricing") ? "The pricing lesson is to charge for the outcome, not your anxiety." : "Growth changed when I started treating one strong idea like a creative asset.", start: q.toLowerCase().includes("pricing") ? 42.8 : 16.2, end: q.toLowerCase().includes("pricing") ? 49.1 : 22.4, assetId: "asset-1" }]),
  getProject: (id: string) => request<{ project: Project; script: Script; mappings: Mapping[]; clips: Clip[] }>(`/projects/${id}`, undefined, () => ({ project: projects.find(p => p.id === id) ?? projects[0], script, mappings, clips })), generateScript: (input: Pick<Script, "topic" | "niche" | "tone" | "platform">) => request<Script>("/scripts/generate", { method: "POST", body: JSON.stringify(input) }, () => ({ ...script, ...input })), generateHooks: (scriptId: string) => request<HookVariant[]>("/hooks/generate", { method: "POST", body: JSON.stringify({ scriptId }) }, () => hooks), mapProject: (projectId: string) => request<Mapping[]>(`/projects/${projectId}/map`, { method: "POST" }, () => mappings), generateClips: (projectId: string) => request<Clip[]>(`/projects/${projectId}/clips/generate`, { method: "POST" }, () => clips), getTimeline: (id: string) => request<Timeline>(`/timelines/${id}`, undefined, () => initialTimeline), updateTimeline: (timeline: Timeline) => request<Timeline>(`/timelines/${timeline.id}`, { method: "PUT", body: JSON.stringify(timeline) }, () => timeline), renderTimeline: (id: string, platform: string) => request<{ renderId: string; status: string }>(`/timelines/${id}/render?platform=${encodeURIComponent(platform)}`, { method: "POST" }, () => ({ renderId: `render-${Date.now()}`, status: "queued" })), getWorkflow: () => request<WorkflowCard[]>("/workflow", undefined, () => workflowCards), updateWorkflow: (card: WorkflowCard) => request<WorkflowCard>(`/workflow/${card.id}`, { method: "PATCH", body: JSON.stringify(card) }, () => card), getInsights: () => request<{ metrics: InsightMetric[] }>("/insights", undefined, () => ({ metrics: insightMetrics })), schedulePost: (post: Omit<ScheduledPost, "id" | "status">) => request<ScheduledPost>("/publish/schedule", { method: "POST", body: JSON.stringify(post) }, () => ({ ...post, id: crypto.randomUUID(), status: "scheduled" })), getScheduledPosts: () => request<ScheduledPost[]>("/publish/schedule", undefined, () => scheduledPosts), assistantCommand: (timelineId: string, command: string) => request<{ command: string; timelineId: string }>("/assistant/command", { method: "POST", body: JSON.stringify({ timelineId, command }) }, () => ({ command, timelineId })), transcript: () => Promise.resolve(transcriptWords),
};
